### ISSUE TITLE
"-f" argument breaks program

### ISSUE THREAD

**Issue by aybri** [MCJack123/sanjuuni-ui#1]
Whenever I run `sanjuuni-ui` with the `-f` argument, it immediately crashes, no window opens. Checked task manager, nothing there.

**Comment by MCJack123** [comment]
This is because any command-line arguments cause it to run as a command-line application. You will need to pass in all relevant parameters for sanjuuni for it to work. Due to Windows, the program cannot output anything to the screen, so that's why there was no output.
